### ISSUE TITLE
Bug in check_functions: wrong ca for chem_potential_water_ice etc.

### ISSUE THREAD

**Issue by efiring** [TEOS-10/GSW-Matlab#10]
https://github.com/TEOS-10/GSW-Matlab/blob/master/Toolbox/gsw_check_functions.m#L1218
and line 1232 have copy/paste leftovers of ca values, `kappa_const_t_ice_ca` instead of those corresponding to their respective variables.

**Comment by PaulMBarker** [comment]
I have made this correction. thanks very much for letting me know.

**Comment by efiring** [comment]
Thank you.  I will leave this and the other issue open until the corrections have landed in this repo.
