### ISSUE TITLE
missing source code for gsw_SAAR?

### ISSUE THREAD

**Issue by efiring** [TEOS-10/GSW-Matlab#3]
The C version of gsw_SAAR segfaults with lon/lat on land, so I wanted to see the original Matlab source.  It is hidden in a .p file.  Why?  Is the intention really to keep it secret?

**Comment by PaulMBarker** [comment]
Sorry I need to update the html help file to include a copy of the actual programme, this is an oversight on my behalf.  I will try and update it this week as I also have bug fix in one of the chemical programmes to include.

We opted to add protection to 3 of the GSW programmes, gsw_gibbs, gsw_gibbs_ice and gsw_SAAR as they are accepted standards and as such we did not want to have any one change any of those values listed
We really just wanted to lock the file or write protect, not encode it but we could not see how to do this in matlab.

In the updated help page it includes the following text.

%  Reference page in Help browser
%       <a href="matlab:doc gsw_SAAR">doc gsw_SAAR</a>
%  Note that this reference page includes the code contained in gsw_SAAR.
%  We have opted to encode this programme as it is a global standard and 
%  such we cannot allow anyone to change it.

The code can be also be seen in the GSW(documentation) section of github
https://github.com/TEOS-10/GSW-documentation/blob/master/html/gsw_SAAR.html

**Comment by PaulMBarker** [comment]
I have just copied the original source codes for gsw_gibbs, gsw_gibbs_ice and gsw_SAAR to github.

**Comment by richardsc** [comment]
Hi @PaulMBarker. Can you push the above noted changes to Github? There are no new commits showing up since the last one 69569b9 on June 15 2016.

Thanks!

**Comment by PaulMBarker** [comment]
As far as I can tell it is uploaded, do you not see it? I am the first to admit I am not very good at git.

**Comment by efiring** [comment]
I see it.  Thank you!
