### ISSUE TITLE
Unnecessary arguments to gsw_Nsquared_lowerlimit

### ISSUE THREAD

**Issue by hylandg** [TEOS-10/GSW-Matlab#4]
```Matlab
function Nsquared_lowerlimit = gsw_Nsquared_lowerlimit(p,long,lat)
```
The `long,lat` arguments aren't actually used anywhere in the code?

**Comment by PaulMBarker** [comment]
They will be in future versions of the code.

**Comment by hylandg** [comment]
Ok, thanks. I'll put them back into the Fortran code.
