### ISSUE TITLE
possible typo in html doc for gsw_alpha_wrt_t_ice

### ISSUE THREAD

**Issue by dankelley** [TEOS-10/GSW-Matlab#5]
The page
http://www.teos-10.org/pubs/gsw/html/gsw_alpha_wrt_t_ice.html

has title "gsw_alpha_wrt_t_exact", and the same word is used in the USAGE block. I think that should be "gsw_alpha_wrt_t_ice" in both cases.

**Comment by PaulMBarker** [comment]
Thanks, I will fix this. Cut and paste caught me out again.
