### ISSUE TITLE
typo in gsw_t_freezing_first_derivatives() and *poly() documented check values?

### ISSUE THREAD

**Issue by dankelley** [TEOS-10/GSW-Matlab#6]
@PaulMBarker -- I think there may be typos in the docs for `gsw_t_freezing_first_derivatives` and `gsw_t_freezing_first_derivatives`. I recently wired up an interface to these functions in the R version (`develop` branch). In my scheme, I always include the test values stated in the HTML pages for the matlab version, and I create build-time tests for the  R package, to ensure adherence to these test values to machine accuracy. I cannot make those tests work fully for either named function. I find that the HTML-published test values fail 3 of the 4 tests. Things are OK for d/dp with the `gsw_t_freezing_first_derivatives_poly` function, but bad for d/dSA for that function, and both derivatives are bad for `gsw_t_freezing_first_derivatives`.

I think my R wrapper is properly working, since in at least the single case I tried, I get identical values to those in the C check suite ... the R code below demonstrates (the two tests at the very bottom show that R is matching C to machine fuzziness, at about 15 digits).

```R
> library(gsw)
> SA <- 34.507499465692057               # gsw_check_data.c:114
> p <- 0                                 # gsw_check_data.c:273
> saturation_fraction <- 0.5             # gsw_check_functions.c:237
> a <- gsw_t_freezing_first_derivatives(SA, p, saturation_fraction)
> expect1 <- -0.056779813903185601       # gsw_check_data.c:6091
> expect2 <- -7.4809414594418683e-08     # gsw_check_data.c:6141
> 
> options(digits=15)
> print(a)
$tfreezing_SA
[1] -0.0567798139031856

$tfreezing_p
[1] -7.48094145944186e-08

> print(expect1)
[1] -0.0567798139031856
> print(expect2)
[1] -7.48094145944187e-08
> print((a$tfreezing_SA-expect1)/expect1)
[1] 2.44414112231457e-16
> print((a$tfreezing_p-expect2)/expect2)
[1] -5.30744286902996e-16
```

**Comment by PaulMBarker** [comment]
I just recalculated the values for the help pages.  see below

SA = [34.7118; 34.8915; 35.0256; 34.8472; 34.7366; 34.7324;]
p =  [     10;      50;     125;     250;     600;    1000;]
saturation_fraction = [1; 0.8; 0.6; 0.5; 0.4; 0;]

[tfreezing_SA, tfreezing_P] = gsw_t_freezing_first_derivatives(SA,p,saturation_fraction)

tfreezing_SA =

  -0.056811800705787
  -0.056856999671114
  -0.056903079789292
  -0.056904020028541
  -0.056974588411844
  -0.057082363270642


tfreezing_P =

   1.0e-07 *

  -0.748468312442338
  -0.749793159537290
  -0.752225023995510
  -0.756170965034610
  -0.767279572670040
  -0.779936552091913

**Comment by PaulMBarker** [comment]
SA = [34.7118; 34.8915; 35.0256; 34.8472; 34.7366; 34.7324;]
p =  [     10;      50;     125;     250;     600;    1000;]
saturation_fraction = [1; 0.8; 0.6; 0.5; 0.4; 0;]

[tfreezing_SA, tfreezing_P] = ...
      gsw_t_freezing_first_derivatives_poly(SA,p,saturation_fraction)

tfreezing_SA =

  -0.056810211094078
  -0.056855567524973
  -0.056901968693345
  -0.056903498206432
  -0.056975157476629
  -0.057083526206200


tfreezing_P =

   1.0e-07 *

  -0.748987354878138
  -0.750288853857513
  -0.752676389629787
  -0.756549680608529
  -0.767482625710990
  -0.779985619685683

**Comment by PaulMBarker** [comment]
I have updated the help pages but can not load them to the web from CASIRO, will try and do it from home tonight.

**Comment by dankelley** [comment]
Thanks, @PaulMBarker. I can confirm that these test values work in GSW-R.  I have put a note in the "Bugs" section in the documentation for these two functions that an update to the official webpage is expected in the future, and when I see that update, I'll remove the warning.

As for closing the present issue report, I think I should leave that up to you. The normal convention would be for the reporter to close an issue when tests show that the issue is no longer relevant to the code on the repo.  However, I do not have access to matlab, so I would not be able to test any update to either this repo or the source code provided on teos-10, so I cannot be the one to close the issue.

**Comment by PaulMBarker** [comment]
you should have complete access to all of the teos-10 directory's on github as you are an owner.

________________________________

**Comment by dankelley** [comment]
Sorry, @PaulMBarker, what I meant is that I don't have access to Matlab, the computer programme. I wasn't referring to the GSW-Matlab repository. I wouldn't want to be the one to try to keep the GSW-Matlab repository in-sync with the official teos-10 source, since I cannot even run Matlab to test things.

Actually, it is not clear to me how (or if) the GSW-Matlab repository will be kept in-sync with the teos-10 source. My focus is mostly on writing R wrappers for the C code, and I have been pointing out issues with the Matlab source as a way to help the whole chain i.e. `matlab -> (Fortran, C, python, R, ...)`
