### ISSUE TITLE
Bug in gsw_check_functions: argument order in gsw_CT_from_enthalpy

### ISSUE THREAD

**Issue by efiring** [TEOS-10/GSW-Matlab#9]
https://github.com/TEOS-10/GSW-Matlab/blob/master/Toolbox/gsw_check_functions.m#L621 has the argument order (h, s, p), but it should be (s, h, p).  Presumably there is a second error somewhere else that is allowing the check to pass.

**Comment by PaulMBarker** [comment]
Thanks for pointing this out I will correct it. I need to make a new release of the matlab to include the corrected help pages but the internet company still seems incapable of sorting it out.
